# Workflow to build and deploy site to AWS using Apex Up
name: deploy-production
on:
  push:
    branches: [ master ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Copy and Prep
      run: |
          cp -avfr html dist
          sed -i "s|{STAGE}|production|g" dist/index.html
          sed -i "s|{STAGE}|production|g" dist/open/index.html
          sed -i "s|{STAGE}|production|g" dist/private/index.html
          sed -i "s|{STAGE}|production|g" dist/private/sub/index.html
    - name: Deploy via Apex Up
      env:
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          UP_CONFIG: ${{ secrets.UP_CONFIG }}
      uses: apex/actions/up@v0.5.1
      with:
        stage: production
    - name: Check folder contents
      run: |
          ls
          echo "====== HTML ======"
          ls html
